// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ammawhrjbwqmwhsbdjoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtbWF3aHJqYndxbXdoc2Jkam9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTExNTUsImV4cCI6MjA3MzU4NzE1NX0.D8gMBK6Zye8zQ7O_ufNlMfnCAypLII54Gl4SDEux22o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});