name: Supabase Deploy (Manual)

on:
  workflow_dispatch: {}  # Körs från GitHub Actions-menyn

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: |
          curl -sL https://app.supabase.com/cli/install | sh
          echo "$HOME/.supabase/bin" >> "$GITHUB_PATH"
          supabase --version

      - name: Deploy edge functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy codes --project-ref ammahwrjbwqmwhsbdjoa
          supabase functions deploy exercises --project-ref ammahwrjbwqmwhsbdjoa
          supabase functions deploy lessons --project-ref ammahwrjbwqmwhsbdjoa

      - name: Push DB migrations
        env:
          SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          supabase db push --db-url "postgresql://postgres:${SERVICE_ROLE_KEY}@db.ammahwrjbwqmwhsbdjoa.supabase.co:5432/postgres"
